### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ogozcelik** [emreozcan/tdk-py#1]
**Describe the bug**
Hi, when I try the function `tdk.gts.search`, I got a connection error as below.

**Output**
`http.client.RemoteDisconnected: Remote end closed connection without response`

**Screenshots**
![error](https://user-images.githubusercontent.com/70253174/162060549-d1b62830-e383-426d-9b1f-68c98d2c8bb2.JPG)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Python Version [e.g. 3.8]

**Comment by emreozcan** [comment]
Thank you very much for letting me know. I was able to reproduce the issue. Investigating.

![resim](https://user-images.githubusercontent.com/47896566/162062689-07b81ebc-12c3-4b6e-959c-2a391db9aed2.png)

**Comment by emreozcan** [comment]
Identified the problem: TDK servers are blocking requests with user agent headers containing the substring `Python`.

![resim](https://user-images.githubusercontent.com/47896566/162064690-c9d2ef50-ba62-43fa-9e3d-ad85991d4463.png)

Fix coming shortly.

**Comment by ogozcelik** [comment]
I guess it can be fixed by using a random agent header as below:
`requests.get("https://sozluk.gov.tr/gts?ara=akaryakıt", headers={
"User-Agent" : "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
})`

**Comment by emreozcan** [comment]
Yes, but I will implement it using `urllib` because I don't want to introduce another dependency. (The `requests` module is not in the standard library.)

**Comment by emreozcan** [comment]
[The fix is live!](https://pypi.org/project/tdk-py/1.1.1/) Sorry for the inconvenience. Thanks again for reporting!

`pip install tdk-py --upgrade` should do it!

İyi araştırmalar, kolay gelsin!
